# Generated by Django 4.0 on 2022-05-10 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='phone',
            field=models.IntegerField(default=1, max_length=10),
        ),
    ]
