# Generated by Django 4.0 on 2022-05-10 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktable', '0002_booking_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
