# Generated by Django 4.0 on 2022-05-10 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booktable', '0008_alter_booking_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='phone',
        ),
    ]
