# Generated by Django 4.0 on 2022-05-10 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktable', '0011_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date_book',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.CharField(default='', max_length=10),
        ),
    ]
