# Generated by Django 4.0 on 2022-05-10 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booktable', '0012_alter_booking_date_book_alter_booking_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='date_book',
            new_name='date',
        ),
    ]
